package boot

import (
	"github.com/fast-crud/fast-auth/app/controller/api"
	"github.com/fast-crud/fast-auth/boot/middleware"
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/net/ghttp"
	"github.com/gogf/gf/v2/util/gmeta"
)

var Routers = new(_router)

type _router struct{}

func (r *_router) bind(group *ghttp.RouterGroup, basePath string, controller interface{}, middlewares ...ghttp.HandlerFunc) {
	var metaPath = gmeta.Get(controller, "path")
	var groupPath = basePath
	if metaPath != nil {
		groupPath += metaPath.String()
	}
	group.Group(groupPath, func(group *ghttp.RouterGroup) {
		if middlewares != nil {
			for i := range middlewares {
				group.Middleware(middlewares[i])
			}
		}

		group.Bind(controller)
	})
}
func (r *_router) Register() {
	g.Server().Use(middleware.ResponseHandler)

	//注册 api 和 manager
	g.Server().Group("", func(group *ghttp.RouterGroup) {
		group.Middleware(middleware.Authentication)
		group.Middleware(middleware.Casbin)

		r.bind(group, "/api", new(api.AuthController))
		r.bind(group, "/api", new(api.UserController))
		r.bind(group, "/api", new(api.CaptchaController))
		r.bind(group, "/manager", new(api.AuthController), middleware.OperationLog)
	})

	//注册 rpc
	g.Server().Group("", func(group *ghttp.RouterGroup) {
		group.Middleware(middleware.BasicAuth)
		r.bind(group, "/rpc", new(api.UserController))
	})

}

//// PublicRouter 公开路由组初始化
//
//func (r *_router) PublicRouter() *_router {
//	public := g.Server().Group("")
//	{
//		system.NewCaptchaGroup(public).Public()
//		system.NewUserRouter(public).Public().PublicWithoutRecord()
//		Plugin.PublicInitialize(public)
//		// Code generated by gf-vue-admin Begin; DO NOT EDIT.
//		// Code generated by gf-vue-admin End; DO NOT EDIT.
//	} // 无需鉴权中间件
//	return r
//}

//
//// PrivateRouter 私有路由组初始化
//
//func (r *_router) PrivateRouter() *_router {
//	private := g.Server().Group("")
//	private.Middleware(middleware.Authentication, middleware.Casbin)
//	{
//		system.NewUserRouter(private).Private().PrivateWithoutRecord()
//		system.NewCasbinRouter(private).Private().PrivateWithoutRecord()
//		system.NewServerRouter(private).Private().PrivateWithoutRecord()
//		system.NewJwtBlacklistRouter(private).Private().PrivateWithoutRecord()
//		system.NewOperationRecordRouter(private).Private().PrivateWithoutRecord()
//
//		example.NewFileRouter(private).Private().PrivateWithoutRecord()
//
//		Plugin.PrivateInitialize(private)
//		// Code generated by gf-vue-admin Begin; DO NOT EDIT.
//		// Code generated by gf-vue-admin End; DO NOT EDIT.
//	} // 需要Jwt鉴权, casbin鉴权
//	return r
//}
