package boot

import (
	"github.com/flipped-aurora/gf-vue-admin/app/controller/api"
	"github.com/flipped-aurora/gf-vue-admin/app/controller/manager"
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/net/ghttp"
)

var Routers = new(_router)

type _router struct{}

func (r *_router) Register() {

	g.Server().Group("/api/user", func(group *ghttp.RouterGroup) {
		group.Bind(new(api.UserController))
	})
	g.Server().Group("/api/captcha", func(group *ghttp.RouterGroup) {
		group.Bind(new(api.CaptchaController))
	})

	g.Server().Group("/manager/user", func(group *ghttp.RouterGroup) {
		group.Bind(new(manager.UserController))
	})
}

//// PublicRouter 公开路由组初始化
//// Author [SliverHorn](https://github.com/SliverHorn)
//func (r *_router) PublicRouter() *_router {
//	public := g.Server().Group("")
//	{
//		system.NewCaptchaGroup(public).Public()
//		system.NewUserRouter(public).Public().PublicWithoutRecord()
//		Plugin.PublicInitialize(public)
//		// Code generated by gf-vue-admin Begin; DO NOT EDIT.
//		// Code generated by gf-vue-admin End; DO NOT EDIT.
//	} // 无需鉴权中间件
//	return r
//}

//
//// PrivateRouter 私有路由组初始化
//// Author [SliverHorn](https://github.com/SliverHorn)
//func (r *_router) PrivateRouter() *_router {
//	private := g.Server().Group("")
//	private.Middleware(middleware.JwtAuth, middleware.Casbin)
//	{
//		system.NewUserRouter(private).Private().PrivateWithoutRecord()
//		system.NewCasbinRouter(private).Private().PrivateWithoutRecord()
//		system.NewServerRouter(private).Private().PrivateWithoutRecord()
//		system.NewJwtBlacklistRouter(private).Private().PrivateWithoutRecord()
//		system.NewOperationRecordRouter(private).Private().PrivateWithoutRecord()
//
//		example.NewFileRouter(private).Private().PrivateWithoutRecord()
//
//		Plugin.PrivateInitialize(private)
//		// Code generated by gf-vue-admin Begin; DO NOT EDIT.
//		// Code generated by gf-vue-admin End; DO NOT EDIT.
//	} // 需要Jwt鉴权, casbin鉴权
//	return r
//}
