# jwt configuration
jwt:
  signing-key: 'SliverHorn'
  buffer-time: 86400
  expires-time: 604800

# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[GF-VUE-ADMIN]'
  director: 'logs'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# gorm configuration
gorm:
  config: 'charset=utf8mb4&parseTime=true&loc=Local'
  log-zap: false
  log-mode: "info"
  auto-migrate: true
  max-idle-conns: 10
  max-open-conns: 100
  conn-max-lifetime: 1h
  conn-max-idle-time: 24h
  dsn:
    sources:
      - host: '127.0.0.1'
        port: '3306'
        db-name: 'fast_auth'
        username: 'root'
        password: 'root'
      - host: ''
        port: ''
        db-name: ''
        username: ''
        password: ''
    replicas:
      - host: ''
        port: ''
        db-name: ''
        username: ''
        password: ''
      - host: ''
        port: ''
        db-name: ''
        username: ''
        password: ''

# redis configuration
redis:
  db: 0
  addr: '127.0.0.1:6379'
  password: ''

# casbin configuration
casbin:
  model-path: './public/rbac_model.conf'

# system configuration
system:
  env: 'public'  # Change to "develop" to skip authentication for development mode
  oss-type: 'local'    # 控制oss选择走本期还是 七牛等其他仓 自行增加其他oss仓可以在 server/utils/upload/upload.go 中 Oss函数配置
  use-multipoint: false

# captcha configuration
captcha:
  key-long: 6
  img-width: 240
  img-height: 80
  verification: false

# auto-code configuration
auto-code:
  root: ''
  server:
    root: ''
    api: '/app/api/example'
    boot: '/boot'
    model: '/app/model/example'
    router: '/app/router/example'
    request: '/app/model/example/request'
    service: '/app/service/example'
  web:
    root: '/web/src'
    api: '/api'
    flow: '/view'
    form: '/view'
    table: '/view'
  restart: false
  rubbish-path: ''

casdoor:
  endpoint: "http://casdoor.docmirror.cn:8000"
  clientId: "5df93cbab9bd641b3254"
  clientSecret: "e199788a17f34ccdacc5c69dd7d18b15bea3034b"
  organization: "handsfree"
  application: "fast-auth"
  jwtPublicKey: "-----BEGIN CERTIFICATE-----\nMIIE+TCCAuGgAwIBAgIDAeJAMA0GCSqGSIb3DQEBCwUAMDYxHTAbBgNVBAoTFENh\nc2Rvb3IgT3JnYW5pemF0aW9uMRUwEwYDVQQDEwxDYXNkb29yIENlcnQwHhcNMjEx\nMjE4MTQzNTExWhcNNDExMjE4MTQzNTExWjA2MR0wGwYDVQQKExRDYXNkb29yIE9y\nZ2FuaXphdGlvbjEVMBMGA1UEAxMMQ2FzZG9vciBDZXJ0MIICIjANBgkqhkiG9w0B\nAQEFAAOCAg8AMIICCgKCAgEArmtICfjqXkf3FGwhjkmPy9x49sYNK+M82qhIA35m\nmtUfxT6uIw22uNFUZe11Tjes8T/T7vilC6QaaSFVqskSIY8ZUKJ73gsbqOaVy2lz\nTQjlNGqiUEingzuCDl8jtsUq0LWyPDLEUQNO2OnAdKGxuOaHDwsvHol+Wfcmu8Vj\nebN7u8u0achS6bwNUMBz7klGME9rZ20Ihb6X8syOE2vkjmDwXEGFhSpxgmqarXyp\nJf7GMAea0dfZlamEU417IOI5xjp2SpdiqkHPfhrqxTBNNk1SNXaCLwuZdAPaRR5B\n1LmLcSE/IhkhwvBMEUehfjLJ8oLhuhJbOD4cgg/mc3U1qTwaMPIMqDQBiaBsYPyT\ngJ2cxOwKlu5KNwJIpZUg8piVRUPgMTcQmTmjT1FJA97y3egDB8F6oMQ1GrUiIiSa\ndOs08LxebgrCM1gPaNM+I4HxXCLJJ8EgHk0QqI6VfC0KcpC9kfqQcOeWlBrng2po\n3YewOlM/c2QxY+CHoul71ec1T56j0QZAmSWjphSJ+qqq5R923BQB4hwC18QdbUwj\nqko6d6AoyHcR8+OZYK/MfUiB2j57acUm8hczlHLOlwqzhnzOlNcb0QmI65ipGMyy\nngMLHYW51obdGDOre3oSLy6ecqfJIIPgAp9GU5tYWgnK81Tu8dAafk4qTeiD1LgL\nPAkCAwEAAaMQMA4wDAYDVR0TAQH/BAIwADANBgkqhkiG9w0BAQsFAAOCAgEAhBXt\nNQjX7AgiYhpvZrvzsDMbCtBtx3twbmzyGstrmECWclC1sye2igwSrebA73GUUKis\nZ4pICvboYlZjRFScMj2DoKQxITSGT8KhT6punpkh7SV/OLQcK5cZgSTEh4pm1CyG\nY0rhzmAFADnITxG1w74RgKkJkPBcn6KsnHLJbVLjfPRLvc+uuspmv++I0eoauwvw\ng/AGrHd2zb9NAdxH7ejLFJ2t7pLNjxu9hngNSXTgSnt35Medydjy265/mumEWnIZ\nXD81W5W/WA0rM+JiymAm24iE+pwggEvCOAHcHW4IVmJCBBuAMQ1iWUaEpOiVBgXW\nCYdEiS+Fd3WJWxt+Xjf4kM+fYmV7CIOYOCiDjW35cBhOpnOpPqpu/JmKS5ytBMUd\ndzDWXM6c2EZFXc598Q42IhmRYQEv8hC7HH+ZU51dERNCugreWtl9gO73ENC4aRXr\ny189tITHwoA4/Fz9oaBT9WpoKF7RuR+eIm0WeR3lJ5+doFcAUderjyz0QzOKMLjx\n7y1+AufUK/TnhiN5OVbjCtOBNLMUj3a1boVTmo4E0JjfI20GQu2oRecSwvcd1Pgb\nLOhxwY1EQ4z112XZYEP7bYdXlYwyksGPk6raFQGqonIpe5yVEQs8l/vRI4MpUZFQ\nQJ7akeMDsXUhggFWP2zjA0zWGvroiZIgsw8v90I=\n-----END CERTIFICATE-----"
