# HTTP Server
server:
  address: ':8199'
  graceful: true
  log-path: './logs/server'
  dump-router-map: true
  access-log-enabled: true
  error-log-enabled: true
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# Logger
logger:
  path: './logs/log'
  level: 'all'
  stdout: true

casdoor:
  endpoint: http://casdoor.docmirror.cm:8000
  clientId: 5df93cbab9bd641b3254
  ClientSecret: e199788a17f34ccdacc5c69dd7d18b15bea3034b
  Organization: handsfree
  Application: fast-auth